# NumPy

Numpy - Numerical Python

Biblioteca Para cálculos matemáticos
Fornece a base matemática necessária para análise de dados,
Aprendizado de Máquina, Estatística, entre outros.

FAcilita:

- A criação de Array e Matrizes
- A leitura de datasets
- Álgebra linear

In [1]:
import numpy as np

Também é possível importar desta forma:

from numpy import *

Lista de Dados Python:
- Conjunto de valores de qualquer tipo:
Ex: lista = [1, 20, 'Texto', True, 2.3]

Array Numpy:
- Conjunto de valores de apenas 1 tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computador;


In [2]:
array_1 = np.array([1, 2, 3, 4, 5])

In [3]:
print(type(array_1))

<class 'numpy.ndarray'>


In [4]:
print(array_1)

[1 2 3 4 5]


In [5]:
print(array_1[1])

2


In [6]:
print(array_1.size)

5


# Propriedades/Atributos do Numpy

In [7]:
#shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [8]:
#Retorna o tipo dos dados armazenados
print(array_1.dtype)

int32


In [9]:
#Retorna o tamanho de cada elemento (quanto ocupa na memória)
print(array_1.itemsize)

4


In [10]:
#Retorna o tamanho de todos os elementos do array (4x5 = 20)
print(array_1.nbytes)

20


# Tipos de Arrays

In [11]:
#Array de Inteiros
array_inteiros = np.array([1, 2, 3, 4, 5])
print(array_inteiros)

[1 2 3 4 5]


In [12]:
#Array de Números Reais
array_reais = np.array([2.5, 1.0, 5.2, 10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [13]:
#Array de Strings
array_strings = np.array(['Python', 'Javascript', 'Java'])
print(array_strings)

['Python' 'Javascript' 'Java']


In [14]:
#Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [17]:
array_reais_forcado = np.array([5, 2, 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]


# Matriz

In [2]:
matriz_1 = np.array([[1, 2], [3, 4], [4, 5], [5, 6]])
print(matriz_1)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]


In [3]:
#A dimensão desta matriz é 4 (Linhas) por 2 (Colunas)
print(matriz_1.shape)

(4, 2)


In [9]:
#Para imprimir, basta informar a "linha" e "colunas" entre colchetes
print(matriz_1[0][1])
#Outra forma de Imprimir
print(matriz_1[2,0])

2
4


In [5]:
print(matriz_1[0][0])

1


In [6]:
print(matriz_1[1][1])

4


In [8]:
print(matriz_1[2][1])

5


In [10]:
print(matriz_1[3,1])

6


In [11]:
#Para substituir também utiliza colchetes
matriz_1[2][1] = 10
print(matriz_1[2][1])

#Outra forma
matriz_1[2,0] = 15
print(matriz_1[2,0])

#Matriz completa com os dados substituídos
print(matriz_1)

10
15
[[ 1  2]
 [ 3  4]
 [15 10]
 [ 5  6]]


# Funções para Array

In [12]:
#cumsum - retorna uma matriz com a soma acumulada dos valores
array_2 = np.array([2, 3, 1, 5, 10])
print(array_2.cumsum())

[ 2  5  6 11 21]


In [13]:
#Arange - Cria uma matriz seguindo a lógica do range nativo do python
array_3 = np.arange(5)
print(array_3)

[0 1 2 3 4]


In [14]:
array_4 = np.arange(2, 10, 2)
print(array_4)

[2 4 6 8]


In [16]:
#Linspace
#Cria um array com elementos espaçados igualmente 
#entre um valor inicial e final
# Linspace(início, fim, quantidade de elementos entre eles)
array_5 = np.linspace(1,  10, 4)
print(array_5)

[ 1.  4.  7. 10.]


In [17]:
#zeros - Cria um array somente com elementos 0
array_6 = np.zeros(15)
print(array_6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Funções para Matriz

In [19]:
#eye - Cria uma matriz quadrada, todos os elementos são zeros com
#exeção dos elementos que formam a diagonal principal, estes
#recebem o valor 1
matriz_2 = np.eye(3)
print(matriz_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
